sudo: false
language: node_js
node_js:
  - 'node'
env:
  - EXTENSION_ID=hnhcdhgekpmjjgdfimnigdeghjhicnea
deploy:
  - provider: releases
    skip_cleanup: true
    overwrite: true
    api_key: $GH_TOKEN
    file_glob: true
    file: "dist/*"
    on:
      branch: master
      tags: true
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: master
      tags: true
